---
title: "LINCs PC3 SS3 Population Level MEMA Data"
date: "`r Sys.Date()`"
output: pdf_document
---
##Summary
This experiment uses the LINCs SS3 on PC3 cells in 8 well MEMAs. 


```{r setup, echo=FALSE, message=FALSE}
library("limma")
library("MEMA")
library("data.table")

```

```{r Read and clean spotmetadata, echo=FALSE, message=FALSE, warnings=FALSE}

#Read in the spot metadata from the gal file
smd <- readSpotMetadata("./Raw Data and Metadata/20150515_LI8X001_v1.gal")
#Make a short name from the content names for labeling in plots
smd$ShortName <- gsub("_.*","",smd$Name)
smd$ShortName <- gsub("-","blank",smd$ShortName)

#Add the print order and deposition number to the metadata
  ldf <- readLogData("./Raw Data and Metadata/20150512-112336.xml")
  spotMetadata <- merge(smd,ldf, all=TRUE)
  setkey(spotMetadata,Spot)
#Make a rotated version of the spot metadata
spotMetadata180 <- rotateMetadata(spotMetadata)
ARowMetadata <- data.table(spotMetadata,Well=rep(c("A01", "A02","A03","A04"),each=nrow(spotMetadata)))
BRowMetadata <- data.table(spotMetadata180,Well=rep(c("B01", "B02","B03","B04"),each=nrow(spotMetadata180)))

```


```{r Teacan merge, normalize and QA, echo=FALSE, message=FALSE, warnings=FALSE}
#The next steps are to bring in the well metadata, the print order and the Tecan intensity  
#data. The Tecan data includes the raw, background and net data values.
popDataFiles <- c("LI8X00120.txt","LI8X00121.txt","LI8X00122.txt","LI8X00123.txt","LI8X00124.txt","LI8X00125.txt")

barcodes <- gsub(".txt","",popDataFiles)

annDTList <- lapply(barcodes, function(barcode){
  #browser(expr=barcode=="LI8X00117")
  spotsPerWell <- max(spotMetadata$Block) * max(spotMetadata$Row) * max(spotMetadata$Column)
  #Read data from one plate
  popData<-fread(paste0("./Raw Data and Metadata/",barcode,".txt"),stringsAsFactors=FALSE)
  #Change the name of the first column
  setnames(popData,1,"Index")
  #Delete the statistical summary after the population data
  popData <- popData[1:spotsPerWell,]
  #Organize the data by well
  popData <- melt8Well(popData)
  setnames(popData,"Grid","Block")
  setkey(popData, Well, Block, Row, Column)
 
  #Merge in the well metadata
 #Read the well metadata from a multi-sheet Excel file
  wellMetadata <- data.table(readMetadata(paste0("./Raw Data and Metadata/",barcode,".xlsx")), key="Well")  
  popData <- merge(popData, wellMetadata, by="Well")
  #Modify the Endpoint names if needed
  if("Endpoint.DAPI" %in% colnames(popData)) setnames(popData,"Endpoint.DAPI","DAPI")
  if("Endpoint.488" %in% colnames(popData)) setnames(popData,"Endpoint.488","Endpoint488")
  if("EndPoint.488" %in% colnames(popData)) setnames(popData,"EndPoint.488","Endpoint488")
  if("Endpoint.555" %in% colnames(popData)) setnames(popData,"Endpoint.555","Endpoint555")
  if("EndPoint.555" %in% colnames(popData)) setnames(popData,"EndPoint.555","Endpoint555")
  if("Endpoint.647" %in% colnames(popData)) setnames(popData,"Endpoint.647","Endpoint647")
  if("EndPoint.647" %in% colnames(popData)) setnames(popData,"EndPoint.647","Endpoint647")

  #write.table(popData, paste0("./Annotated Data/",barcode,"PopAnn.txt"), sep = "\t",row.names = FALSE, quote=FALSE)
  return(popData)
})
annDT <- rbindlist(annDTList, use.names=TRUE, fill=TRUE)
#Merge the data with spot metadata that is well row specific
sDT <- merge(annDT,rbind(ARowMetadata,BRowMetadata), by = c("Well","Block","Row","Column"), all=TRUE)

#Add the median normalized loess values of each channel on a per well basis
sDT <- sDT[,Loess488 := loessModel(.SD,value="Net.488",span=.1), by="Barcode,Well"]
sDT <- sDT[,Loess555 := loessModel(.SD,value="Net.532",span=.1), by="Barcode,Well"]
sDT <- sDT[,Loess647 := loessModel(.SD,value="Net.635",span=.1), by="Barcode,Well"]

#Median normalize to the plate's control well for each channel's Net value
sDT <- sDT[,Net.488.MedNorm := normWellsWithinPlate(.SD, value="Net.488", baseECM = ".*",baseGF = "HighSerum"), by="Barcode"]
sDT <- sDT[,Net.532.MedNorm := normWellsWithinPlate(.SD, value="Net.532", baseECM = ".*",baseGF = "HighSerum"), by="Barcode"]
sDT <- sDT[,Net.635.MedNorm := normWellsWithinPlate(.SD, value="Net.635", baseECM = ".*",baseGF = "HighSerum"), by="Barcode"]

#Add randomized version of the normalized CellMask signal
sDT <- sDT[,Net.532.MedNorm.Random := randomizePositions(Net.532.MedNorm), by="Barcode,Well"]


write.table(sDT, paste0("./Annotated Data/LI8X00120_27PopAnn.txt"), sep = "\t",row.names = FALSE, quote=FALSE)

```
